# Generated by Django 4.2.19 on 2025-04-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
