# Generated by Django 4.2.19 on 2025-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_deliveryperson_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
