# Generated by Django 4.2.19 on 2025-04-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_chef_created_at_alter_manager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='restaurant.restaurant'),
        ),
    ]
