# Generated by Django 4.2.19 on 2025-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingredient_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Liter (L)'), ('ml', 'Milliliter (ml)'), ('pc', 'Piece (pc)'), ('tsp', 'Teaspoon (tsp)'), ('tbsp', 'Tablespoon (tbsp)')], default='g', max_length=10),
        ),
    ]
