# Generated by Django 4.2.19 on 2025-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('seafood', 'Seafood'), ('grains', 'Grains'), ('spices', 'Spices'), ('oils', 'Oils'), ('nuts', 'Nuts'), ('herbs', 'Herbs'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
