# Generated by Django 4.2.19 on 2025-04-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_dishingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.dailymenu')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailymenudish',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='dailymenudish',
            name='current_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailymenudish',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Liter (L)'), ('ml', 'Milliliter (ml)'), ('pc', 'Piece (pc)'), ('tsp', 'Teaspoon (tsp)'), ('tbsp', 'Tablespoon (tbsp)')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.shoppinglist')),
            ],
        ),
    ]
