# Generated by Django 4.2.19 on 2025-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_shoppinglist_remove_dailymenudish_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='required_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
