# Generated by Django 4.2.19 on 2025-04-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_shoppinglistitem_required_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='required_quantity',
            field=models.FloatField(),
        ),
    ]
