# Generated by Django 5.1.7 on 2025-05-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_table_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=30),
        ),
    ]
